# Generated by Django 6.0.2 on 2026-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipie_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image_url",
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_pics/"),
        ),
    ]
