# Generated by Django 6.0.2 on 2026-02-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipie_app", "0002_remove_recipe_image_url_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Recipie_app.category",
            ),
        ),
    ]
