# Generated by Django 6.0 on 2026-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
